### ISSUE TITLE
Explain the # symbol

### ISSUE THREAD

**Issue by valrus** [alhassy/ElispCheatSheet#2]
I often see `#` in existing Elisp code and always forget what it means. It might not be super important to the neophyte Elisp programmer trying to _write_ Elisp, but for those of us trying to _understand_ it, `#` shows up often enough to be confusing and daunting! I think it would be good to include at least a cursory note about what it's for.

**Comment by alhassy** [comment]
Latest commit addresses this; thanks for pointing it out ^_^
